server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/accounts/**
        - id: transaction-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/transactions/**
        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/notifications/**
